# Generated by Django 4.1.2 on 2022-10-18 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'verbose_name': 'Опросный лист', 'verbose_name_plural': 'Опросные листы'},
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
