# Generated by Django 4.1.2 on 2022-10-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_client_options_alter_questionnaire_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='path',
            field=models.CharField(blank=True, max_length=50, verbose_name='Путь до файла'),
        ),
    ]
