# Generated by Django 4.1.2 on 2022-10-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_questionnaire_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='system',
            field=models.CharField(blank=True, choices=[('heating', 'Отопление'), ('water_supply', 'Водоснабжение'), ('pumping_station', 'КНС'), ('firefighting', 'Пожаротушение')], max_length=30, verbose_name='Система'),
        ),
    ]
