# Generated by Django 4.1.2 on 2022-10-21 12:39

from django.db import migrations, models
import json.decoder
import json.encoder
import mfmk_web_app.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_questionnaire_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='engine_data',
            field=models.JSONField(blank=True, decoder=json.decoder.JSONDecoder, default=mfmk_web_app.apps.core.models.Questionnaire.default_json, encoder=json.encoder.JSONEncoder, verbose_name='Данные электродвигателей'),
        ),
    ]
