# Generated by Django 4.1.2 on 2022-10-23 13:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_questionnaire_engine_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='sup_parameter',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('pressure', 'Давление'), ('temperature', 'Температура'), ('flow', 'Расход'), ('level', 'Уровень')], max_length=30, verbose_name='Поддерживаемый параметр'),
        ),
    ]
