# Generated by Django 4.1.2 on 2022-10-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_questionnaire_sup_parameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='for_each',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='one_freq',
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='engine_control',
            field=models.CharField(blank=True, choices=[('direct', 'Прямой пуск'), ('smooth', 'Плавный пуск'), ('frequency', 'Частотное регулирование'), ('one_freq', 'Один преобразователь частоты'), ('for_each', 'ПЧ на каждый электродвигатель')], max_length=50, verbose_name='Управление двигателями'),
        ),
    ]
