# Generated by Django 4.1.2 on 2022-10-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_questionnaire_client_questionnaire_main_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=200, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='entity_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Фамилия, имя, отчество'),
        ),
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.CharField(blank=True, max_length=200, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='post',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность'),
        ),
    ]
