# Generated by Django 4.1.2 on 2023-02-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_client_city_alter_client_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('type', models.CharField(choices=[('closet', 'Шкаф'), ('switching', 'Коммутационное оборудование'), ('softstarter', 'Пч и упп'), ('controllers', 'Контроллеры'), ('avr', 'Авр'), ('tires', 'Шины'), ('signalfittings', 'Сигнальная арматура и переключатели'), ('relays', 'Клеммы и реле'), ('consumables', 'Расходные материалы')], max_length=30, verbose_name='Тип')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Название')),
                ('vendor_code', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Производитель')),
                ('price', models.PositiveIntegerField(blank=True, verbose_name='Цена без НДС')),
                ('currency', models.CharField(choices=[('rub', 'Рубль'), ('usd', 'Доллар'), ('eur', 'Евро')], default='rub', max_length=30, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Позиции',
            },
        ),
    ]
