# Generated by Django 4.1.2 on 2023-02-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pricelist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelist',
            options={'ordering': ('type',), 'verbose_name': 'Прайс-лист', 'verbose_name_plural': 'Позиции'},
        ),
    ]
