# Generated by Django 4.1.2 on 2023-02-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_pricelist_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelist',
            options={'ordering': ('type',), 'verbose_name': 'Позиция', 'verbose_name_plural': 'Прайс-лист'},
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='price',
            field=models.FloatField(blank=True, verbose_name='Цена без НДС'),
        ),
    ]
